adx_appendquerystring: false
adx_associatecurrentportaluser: false
adx_attachfile: false
adx_attachfileallowmultiple: false
adx_attachfilerequired: false
adx_attachfilerestrictaccept: false
adx_autogeneratesteps: false
adx_captcharequired: false
adx_entityformid: e2dc0435-e481-eb11-a812-000d3a3b2ab4
adx_entityname: ait_portalenrollmentapplication
adx_entitypermissionsenabled: false
adx_forceallfieldsrequired: false
adx_formname: Enrollment Application Portal Form
adx_geolocation_displaymap: false
adx_geolocation_enabled: false
adx_geolocation_maptype: 756150000
adx_hideformonsuccess: true
adx_mode: 100000000
adx_name: Enrollment Application S2 - Insert
adx_onsuccess: 756150000
adx_populatereferenceentitylookupfield: false
adx_portaluserlookupattributeisactivityparty: false
adx_recommendedfieldsrequired: false
adx_recordsourceallowcreateonnull: false
adx_redirecturlappendentityidquerystring: false
adx_referenceentityshowreadonlyform: false
adx_referencequerystringisprimarykey: true
adx_renderwebresourcesinline: false
adx_setentityreference: false
adx_showcaptchaforauthenticatedusers: false
adx_showownerfields: false
adx_showunsupportedfields: false
adx_tabname: SectionII
adx_tooltipenabled: false
adx_validationsummarylinksenabled: true
statecode: 1
statuscode: 2
