adx_append: true
adx_appendto: true
adx_contactrelationship: ait_programapplications_Contact_Contact
adx_create: true
adx_delete: false
adx_entitylogicalname: ait_programapplications
adx_entityname: Enrollment Applications
adx_entitypermission_webrole:
- 73aa6040-261e-eb11-a813-000d3a31cf04
- bde7522a-3a52-4619-8531-b022b9c5104f
adx_entitypermissionid: 80bb6b51-ea81-eb11-a812-000d3a3b2ab4
adx_read: true
adx_scope: 756150001
adx_write: true
