adx_displayorder: 72
adx_enablerating: false
adx_enabletracking: false
adx_excludefromsearch: false
adx_feedbackpolicy: 756150000
adx_hiddenfromsitemap: false
adx_isroot: false
adx_name: KenTest Application Detail
adx_pagetemplateid: 367d578e-9f82-eb11-a812-000d3a3b2ab4
adx_parentpageid: 87cdfb86-e3c8-48d7-8a99-c6fb2cbcb845
adx_partialurl: kentestapplicationdetail
adx_publishingstateid: 38c7d71a-31fd-4c2a-b7b0-fa2cc7381654
adx_rootwebpageid: 98c7d354-6799-eb11-b1ac-0022480a05e8
adx_sharedpageconfiguration: true
adx_webpageid: 9cc7d354-6799-eb11-b1ac-0022480a05e8
adx_webpagelanguageid: d9e7ed64-7337-47a8-af6e-35a783c2e2dd
statecode: 1
statuscode: 2
