adx_allowmultiplefiles: false
adx_appendquerystring: false
adx_associatecurrentportaluser: false
adx_attachfile: false
adx_attachfilerequired: false
adx_attachfilerestrictaccept: false
adx_attachfilestoragelocation: 756150000
adx_autogeneratesteps: false
adx_captcharequired: false
adx_createautonumber: false
adx_editexistingrecordpermitted: false
adx_entitypermissionsenabled: true
adx_entitysourcetype: 100000001
adx_forceallfieldsrequired: false
adx_formname: Portal Insert - Education Assessments
adx_geolocation_displaymap: false
adx_geolocation_enabled: false
adx_geolocation_maptype: 756150000
adx_hideformonsuccess: true
adx_loguser: false
adx_maximumnooffiles: 5
adx_mode: 100000001
adx_movepreviouspermitted: true
adx_multiplerecordsperuserpermitted: false
adx_name: 1 - Edit Application Details
adx_nextstep: d4e59ceb-f992-ef11-ac21-000d3a3b9861
adx_populatereferenceentitylookupfield: false
adx_portaluserlookupattributeisactivityparty: false
adx_primarykeyattributelogicalname: ait_educationassessmentid
adx_primarykeyquerystringparametername: ait_educationassessmentid
adx_recommendedfieldsrequired: false
adx_redirecturlappendentityidquerystring: false
adx_referenceentityshowreadonlyform: false
adx_referenceentitysourcetype: 100000001
adx_referencequerystringisprimarykey: true
adx_renderwebresourcesinline: false
adx_setentityreference: false
adx_showcaptchaforauthenticatedusers: false
adx_showownerfields: false
adx_showunsupportedfields: false
adx_tabname: tab_8
adx_targetentitylogicalname: ait_educationassessment
adx_tooltipenabled: false
adx_type: 100000001
adx_validationsummarylinksenabled: true
adx_webform: 262a85af-a985-ef11-ac21-000d3a5b0e68
adx_webformstepid: 22c62865-f992-ef11-ac21-000d3a3b9861
