adx_allowmultiplefiles: false
adx_appendquerystring: false
adx_associatecurrentportaluser: true
adx_attachfile: false
adx_attachfilelabel: >-
  [

    {

      "LCID": 1033,

      "Value": ""

    }

  ]
adx_attachfilerequired: false
adx_attachfilerestrictaccept: false
adx_attachfilestoragelocation: 756150000
adx_autogeneratesteps: false
adx_captcharequired: false
adx_createautonumber: false
adx_editexistingrecordpermitted: false
adx_entitypermissionsenabled: true
adx_forceallfieldsrequired: false
adx_formname: Portal Insert - Education Assessments
adx_geolocation_displaymap: false
adx_geolocation_enabled: false
adx_geolocation_maptype: 756150000
adx_hideformonsuccess: true
adx_loguser: false
adx_maximumnooffiles: 5
adx_mode: 100000000
adx_movepreviouspermitted: true
adx_multiplerecordsperuserpermitted: false
adx_name: 1 - Application Details
adx_nextstep: eb5731a1-7853-ef11-a317-6045bd0807e0
adx_populatereferenceentitylookupfield: false
adx_portaluserlookupattributeisactivityparty: false
adx_primarykeyattributelogicalname: ait_servicerequestid
adx_primarykeyquerystringparametername: id
adx_recommendedfieldsrequired: false
adx_recordsourcerelationshipname: ait_contact_ait_servicerequest_Contact
adx_redirecturlappendentityidquerystring: false
adx_referenceentitylogicalname: ait_educationassessment
adx_referenceentityrelationshipname: ait_educationassessment_ServiceRequest_ait_se
adx_referenceentityshowreadonlyform: false
adx_referenceentitysourcetype: 100000001
adx_referencequerystringisprimarykey: true
adx_renderwebresourcesinline: false
adx_setentityreference: false
adx_showcaptchaforauthenticatedusers: false
adx_showownerfields: false
adx_showunsupportedfields: false
adx_tabname: tab_8
adx_targetentitylogicalname: ait_educationassessment
adx_targetentityportaluserlookupattribute: ait_contact
adx_tooltipenabled: false
adx_type: 100000001
adx_validationsummarylinksenabled: true
adx_webform: 0382d6e9-7753-ef11-a317-6045bd0807e0
adx_webformstepid: 53936716-7853-ef11-a317-6045bd0807e0
