- adx_adddescription: false
  adx_attributelogicalname: ait_servicerequestdate
  adx_descriptionposition: 100000000
  adx_fieldisrequired: false
  adx_ignoredefaultvalue: false
  adx_onsavefromattribute: createdon
  adx_onsavetype: 100000001
  adx_prepopulatetype: 100000001
  adx_purchasecreateinvoiceonpayment: false
  adx_purchasefulfillorderonpayment: false
  adx_purchaserequiresshipping: false
  adx_randomizeoptionsetvalues: false
  adx_setvalueonsave: false
  adx_type: 100000000
  adx_useattributedescriptionproperty: false
  adx_webformmetadataid: 004cd75e-1c8b-ef11-ac21-000d3a3b9861
  adx_webformstep: 53936716-7853-ef11-a317-6045bd0807e0
- adx_adddescription: false
  adx_attributelogicalname: ait_servicerequesttype
  adx_descriptionposition: 100000000
  adx_fieldisrequired: false
  adx_ignoredefaultvalue: false
  adx_onsavetype: 100000000
  adx_onsavevalue: 748120002
  adx_purchasecreateinvoiceonpayment: false
  adx_purchasefulfillorderonpayment: false
  adx_purchaserequiresshipping: false
  adx_randomizeoptionsetvalues: false
  adx_setvalueonsave: true
  adx_type: 100000000
  adx_useattributedescriptionproperty: false
  adx_webformmetadataid: 53fc61c7-1b8b-ef11-ac21-000d3a3b9861
  adx_webformstep: 53936716-7853-ef11-a317-6045bd0807e0
- adx_adddescription: false
  adx_attributelogicalname: ait_createdonportal
  adx_descriptionposition: 100000000
  adx_fieldisrequired: false
  adx_ignoredefaultvalue: false
  adx_onsavetype: 100000000
  adx_onsavevalue: 1
  adx_purchasecreateinvoiceonpayment: false
  adx_purchasefulfillorderonpayment: false
  adx_purchaserequiresshipping: false
  adx_randomizeoptionsetvalues: false
  adx_setvalueonsave: true
  adx_type: 100000000
  adx_useattributedescriptionproperty: false
  adx_webformmetadataid: 8cb0c64f-c181-ef11-ac21-000d3a3b9861
  adx_webformstep: 53936716-7853-ef11-a317-6045bd0807e0
