adx_appendquerystring: false
adx_associatecurrentportaluser: true
adx_attachfile: true
adx_attachfileallowmultiple: true
adx_attachfilerequired: false
adx_attachfilerestrictaccept: false
adx_attachfilesaveoption: 756150000
adx_attachfilestoragelocation: 756150000
adx_autogeneratesteps: false
adx_captcharequired: false
adx_entityformid: d2debfeb-7f9c-eb11-b1ac-000d3a3aee0f
adx_entityname: ait_programapplications
adx_entitypermissionsenabled: true
adx_entitysourcetype: 756150001
adx_forceallfieldsrequired: false
adx_formname: Enrollment Application Details Portal Form
adx_geolocation_displaymap: false
adx_geolocation_enabled: false
adx_geolocation_maptype: 756150000
adx_hideformonsuccess: true
adx_mode: 100000001
adx_name: Enrollment Application - Edit
adx_onsuccess: 756150000
adx_populatereferenceentitylookupfield: false
adx_portaluserlookupattributeisactivityparty: false
adx_recommendedfieldsrequired: false
adx_recordidquerystringparametername: id
adx_recordsourceallowcreateonnull: false
adx_redirecturlappendentityidquerystring: false
adx_referenceentityshowreadonlyform: false
adx_referencequerystringisprimarykey: true
adx_renderwebresourcesinline: false
adx_setentityreference: false
adx_showcaptchaforauthenticatedusers: false
adx_showownerfields: false
adx_showunsupportedfields: false
adx_tabname: ApplicationforSelforChild
adx_targetentityportaluserlookupattribute: ait_contact
adx_tooltipenabled: false
adx_validationsummarylinksenabled: true
